import 'package:flutter/material.dart';

enum ExerciseCategory {
  chest,
  back,
  shoulders,
  biceps,
  triceps,
  legs,
  core,
  cardio,
  fullBody,
}

enum ExerciseType {
  strength, // Weight training
  bodyweight, // Calisthenics
  cardio,
}

class Exercise {
  final String id;
  final String name;
  final ExerciseCategory category;
  final ExerciseType type;
  final String description;
  final double caloriesPerMinute; // Base calories burned per minute
  final double metValue; // Metabolic Equivalent of Task
  final List<String> musclesWorked;
  final String? equipment;
  final IconData icon;
  final bool isUnilateral; // True for single-arm/leg exercises (2x weight)

  Exercise({
    required this.id,
    required this.name,
    required this.category,
    required this.type,
    required this.description,
    required this.caloriesPerMinute,
    required this.metValue,
    required this.musclesWorked,
    this.equipment,
    required this.icon,
    this.isUnilateral = false,
  });

  // Calculate calories burned based on user weight, duration, and intensity
  double calculateCalories({
    required double userWeightKg,
    required int durationMinutes,
    double intensityMultiplier = 1.0,
  }) {
    // Formula: Calories = (MET × weight in kg × duration in hours) × intensity
    final hours = durationMinutes / 60.0;
    return (metValue * userWeightKg * hours * intensityMultiplier);
  }
}

class WorkoutSet {
  final int reps;
  final double weight; // in kg (0 for bodyweight)
  final int restSeconds;

  WorkoutSet({
    required this.reps,
    required this.weight,
    this.restSeconds = 60,
  });

  Map<String, dynamic> toJson() => {
    'reps': reps,
    'weight': weight,
    'restSeconds': restSeconds,
  };

  factory WorkoutSet.fromJson(Map<String, dynamic> json) {
    return WorkoutSet(
      reps: json['reps'] ?? 0,
      weight: json['weight'] ?? 0.0,
      restSeconds: json['restSeconds'] ?? 60,
    );
  }
}

class WorkoutExercise {
  final String exerciseId;
  final List<WorkoutSet> sets;
  final DateTime timestamp;
  final int totalCaloriesBurned;

  WorkoutExercise({
    required this.exerciseId,
    required this.sets,
    required this.timestamp,
    required this.totalCaloriesBurned,
  });

  Map<String, dynamic> toJson() => {
    'exerciseId': exerciseId,
    'sets': sets.map((s) => s.toJson()).toList(),
    'timestamp': timestamp.toIso8601String(),
    'totalCaloriesBurned': totalCaloriesBurned,
  };

  factory WorkoutExercise.fromJson(Map<String, dynamic> json) {
    return WorkoutExercise(
      exerciseId: json['exerciseId'] ?? '',
      sets: (json['sets'] as List?)?.map((s) => WorkoutSet.fromJson(s)).toList() ?? [],
      timestamp: DateTime.parse(json['timestamp']),
      totalCaloriesBurned: json['totalCaloriesBurned'] ?? 0,
    );
  }
}

// Comprehensive exercise library
class ExerciseLibrary {
  static final List<Exercise> exercises = [
    // ========== CHEST EXERCISES ==========
    Exercise(
      id: 'bench_press',
      name: 'Bench Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Classic chest exercise using barbell or dumbbells',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Pectorals', 'Triceps', 'Anterior Deltoids'],
      equipment: 'Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'incline_bench',
      name: 'Incline Bench Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Targets upper chest with inclined bench',
      caloriesPerMinute: 6.2,
      metValue: 6.2,
      musclesWorked: ['Upper Pectorals', 'Anterior Deltoids', 'Triceps'],
      equipment: 'Incline Bench, Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'decline_bench',
      name: 'Decline Bench Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Targets lower chest with declined bench',
      caloriesPerMinute: 5.8,
      metValue: 5.8,
      musclesWorked: ['Lower Pectorals', 'Triceps'],
      equipment: 'Decline Bench, Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'push_ups',
      name: 'Push-ups',
      category: ExerciseCategory.chest,
      type: ExerciseType.bodyweight,
      description: 'Classic bodyweight chest exercise',
      caloriesPerMinute: 7.0,
      metValue: 8.0,
      musclesWorked: ['Pectorals', 'Triceps', 'Core'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'dumbbell_flyes',
      name: 'Dumbbell Flyes',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Isolation exercise for chest with stretch',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Pectorals'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'cable_crossover',
      name: 'Cable Crossover',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Cable isolation for chest peak contraction',
      caloriesPerMinute: 4.8,
      metValue: 4.8,
      musclesWorked: ['Pectorals'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'pec_deck',
      name: 'Pec Deck',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Machine chest fly for isolation',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Pectorals'],
      equipment: 'Pec Deck Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'dumbbell_pullover',
      name: 'Dumbbell Pullover',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Chest and lat expansion exercise',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Pectorals', 'Lats', 'Serratus'],
      equipment: 'Dumbbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'dips_chest',
      name: 'Chest Dips',
      category: ExerciseCategory.chest,
      type: ExerciseType.bodyweight,
      description: 'Leaning forward dips for chest',
      caloriesPerMinute: 7.0,
      metValue: 7.5,
      musclesWorked: ['Lower Pectorals', 'Triceps'],
      equipment: 'Dip Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'svend_press',
      name: 'Svend Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Plate press for inner chest',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Inner Pectorals'],
      equipment: 'Weight Plate',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'incline_dumbbell_flyes',
      name: 'Incline Dumbbell Flyes',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Upper chest isolation',
      caloriesPerMinute: 4.7,
      metValue: 4.7,
      musclesWorked: ['Upper Pectorals'],
      equipment: 'Dumbbells, Incline Bench',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'landmine_press',
      name: 'Landmine Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Angular pressing for upper chest',
      caloriesPerMinute: 5.5,
      metValue: 5.5,
      musclesWorked: ['Upper Pectorals', 'Shoulders'],
      equipment: 'Barbell, Landmine',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'diamond_pushups',
      name: 'Diamond Push-ups',
      category: ExerciseCategory.chest,
      type: ExerciseType.bodyweight,
      description: 'Close-grip push-ups for inner chest and triceps',
      caloriesPerMinute: 7.5,
      metValue: 8.5,
      musclesWorked: ['Inner Pectorals', 'Triceps'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'archer_pushups',
      name: 'Archer Push-ups',
      category: ExerciseCategory.chest,
      type: ExerciseType.bodyweight,
      description: 'Advanced unilateral push-up variation',
      caloriesPerMinute: 8.0,
      metValue: 9.0,
      musclesWorked: ['Pectorals', 'Shoulders', 'Core'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'decline_pushups',
      name: 'Decline Push-ups',
      category: ExerciseCategory.chest,
      type: ExerciseType.bodyweight,
      description: 'Feet elevated push-ups for upper chest',
      caloriesPerMinute: 7.8,
      metValue: 8.5,
      musclesWorked: ['Upper Pectorals', 'Shoulders'],
      icon: Icons.accessibility_new,
    ),

    // ========== BACK EXERCISES ==========
    Exercise(
      id: 'deadlift',
      name: 'Deadlift',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Compound exercise for entire posterior chain',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Lower Back', 'Glutes', 'Hamstrings', 'Traps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'pull_ups',
      name: 'Pull-ups',
      category: ExerciseCategory.back,
      type: ExerciseType.bodyweight,
      description: 'Vertical pulling bodyweight exercise',
      caloriesPerMinute: 7.5,
      metValue: 8.0,
      musclesWorked: ['Lats', 'Biceps', 'Rhomboids'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'chin_ups',
      name: 'Chin-ups',
      category: ExerciseCategory.back,
      type: ExerciseType.bodyweight,
      description: 'Underhand grip pull-ups for biceps and lats',
      caloriesPerMinute: 7.5,
      metValue: 8.0,
      musclesWorked: ['Lats', 'Biceps', 'Lower Lats'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'barbell_row',
      name: 'Barbell Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Horizontal pulling exercise for back thickness',
      caloriesPerMinute: 6.5,
      metValue: 6.5,
      musclesWorked: ['Lats', 'Rhomboids', 'Traps', 'Biceps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'lat_pulldown',
      name: 'Lat Pulldown',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Machine exercise for lat width',
      caloriesPerMinute: 5.5,
      metValue: 5.5,
      musclesWorked: ['Lats', 'Biceps'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'dumbbell_row',
      name: 'Single-Arm Dumbbell Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Unilateral back exercise for thickness',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Lats', 'Rhomboids', 'Traps'],
      equipment: 'Dumbbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 't_bar_row',
      name: 'T-Bar Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Mid-back thickness builder',
      caloriesPerMinute: 6.8,
      metValue: 6.8,
      musclesWorked: ['Mid Back', 'Lats', 'Rhomboids'],
      equipment: 'T-Bar',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'seated_cable_row',
      name: 'Seated Cable Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Cable row for mid-back development',
      caloriesPerMinute: 5.8,
      metValue: 5.8,
      musclesWorked: ['Mid Back', 'Lats', 'Biceps'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'face_pulls',
      name: 'Face Pulls',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Rear delt and upper back exercise',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Rear Deltoids', 'Upper Back', 'Traps'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'pendlay_row',
      name: 'Pendlay Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Explosive barbell row from floor',
      caloriesPerMinute: 7.0,
      metValue: 7.0,
      musclesWorked: ['Upper Back', 'Lats', 'Traps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'inverted_row',
      name: 'Inverted Row',
      category: ExerciseCategory.back,
      type: ExerciseType.bodyweight,
      description: 'Bodyweight horizontal pulling',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Upper Back', 'Lats', 'Biceps'],
      equipment: 'Bar or Rings',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'wide_grip_pullups',
      name: 'Wide Grip Pull-ups',
      category: ExerciseCategory.back,
      type: ExerciseType.bodyweight,
      description: 'Emphasizes lat width',
      caloriesPerMinute: 7.8,
      metValue: 8.5,
      musclesWorked: ['Lats', 'Teres Major'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'meadows_row',
      name: 'Meadows Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Landmine single-arm row',
      caloriesPerMinute: 6.2,
      metValue: 6.2,
      musclesWorked: ['Lats', 'Upper Back'],
      equipment: 'Landmine, Barbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'rack_pulls',
      name: 'Rack Pulls',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Partial deadlift for upper back and traps',
      caloriesPerMinute: 7.5,
      metValue: 7.5,
      musclesWorked: ['Upper Back', 'Traps', 'Lower Back'],
      equipment: 'Barbell, Rack',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'straight_arm_pulldown',
      name: 'Straight-Arm Pulldown',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Lat isolation exercise',
      caloriesPerMinute: 4.8,
      metValue: 4.8,
      musclesWorked: ['Lats'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'shrugs',
      name: 'Barbell Shrugs',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Trap isolation exercise',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Traps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'muscle_up',
      name: 'Muscle-up',
      category: ExerciseCategory.back,
      type: ExerciseType.bodyweight,
      description: 'Advanced pull-up to dip transition',
      caloriesPerMinute: 9.0,
      metValue: 10.0,
      musclesWorked: ['Lats', 'Chest', 'Triceps', 'Core'],
      equipment: 'Pull-up Bar or Rings',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'seal_row',
      name: 'Seal Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Chest-supported row to eliminate cheating',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Upper Back', 'Lats'],
      equipment: 'Bench, Barbell',
      icon: Icons.fitness_center,
    ),

    // ========== SHOULDER EXERCISES ==========
    Exercise(
      id: 'overhead_press',
      name: 'Overhead Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Primary shoulder mass builder',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Deltoids', 'Triceps', 'Upper Chest'],
      equipment: 'Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'lateral_raise',
      name: 'Lateral Raise',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Isolation for side deltoids',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Lateral Deltoids'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'front_raise',
      name: 'Front Raise',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Isolation for front deltoids',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Anterior Deltoids'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'arnold_press',
      name: 'Arnold Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Rotating dumbbell press for complete shoulder development',
      caloriesPerMinute: 6.2,
      metValue: 6.2,
      musclesWorked: ['Deltoids', 'Triceps'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'rear_delt_fly',
      name: 'Rear Delt Fly',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Isolation for rear deltoids',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Rear Deltoids'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'upright_row',
      name: 'Upright Row',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Shoulder and trap builder',
      caloriesPerMinute: 5.5,
      metValue: 5.5,
      musclesWorked: ['Lateral Deltoids', 'Traps'],
      equipment: 'Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'cable_lateral_raise',
      name: 'Cable Lateral Raise',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Constant tension lateral raise',
      caloriesPerMinute: 4.2,
      metValue: 4.2,
      musclesWorked: ['Lateral Deltoids'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'pike_pushups',
      name: 'Pike Push-ups',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.bodyweight,
      description: 'Bodyweight shoulder exercise',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Deltoids', 'Triceps'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'handstand_pushup',
      name: 'Handstand Push-up',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.bodyweight,
      description: 'Advanced vertical push exercise',
      caloriesPerMinute: 8.5,
      metValue: 9.5,
      musclesWorked: ['Deltoids', 'Triceps', 'Core'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'military_press',
      name: 'Military Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Strict overhead press',
      caloriesPerMinute: 6.5,
      metValue: 6.5,
      musclesWorked: ['Deltoids', 'Triceps', 'Core'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'dumbbell_shoulder_press',
      name: 'Dumbbell Shoulder Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Seated or standing dumbbell press',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Deltoids', 'Triceps'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'behind_neck_press',
      name: 'Behind-the-Neck Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Overhead press behind the head',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Deltoids', 'Traps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'reverse_pec_deck',
      name: 'Reverse Pec Deck',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Machine rear delt fly',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Rear Deltoids'],
      equipment: 'Pec Deck Machine',
      icon: Icons.fitness_center,
    ),

    // ========== BICEPS EXERCISES ==========
    Exercise(
      id: 'barbell_curl',
      name: 'Barbell Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Classic bicep mass builder',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Biceps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'dumbbell_curl',
      name: 'Dumbbell Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Standard bicep curl with dumbbells',
      caloriesPerMinute: 4.3,
      metValue: 4.3,
      musclesWorked: ['Biceps'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'hammer_curl',
      name: 'Hammer Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Targets brachialis and forearms',
      caloriesPerMinute: 4.2,
      metValue: 4.2,
      musclesWorked: ['Biceps', 'Brachialis', 'Forearms'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'preacher_curl',
      name: 'Preacher Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Isolated bicep curl on preacher bench',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Biceps'],
      equipment: 'Preacher Bench, Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'concentration_curl',
      name: 'Concentration Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Single-arm bicep isolation',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Biceps'],
      equipment: 'Dumbbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'cable_curl',
      name: 'Cable Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Constant tension bicep curl',
      caloriesPerMinute: 4.3,
      metValue: 4.3,
      musclesWorked: ['Biceps'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'incline_dumbbell_curl',
      name: 'Incline Dumbbell Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Bicep curl on incline bench for full stretch',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Biceps'],
      equipment: 'Incline Bench, Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'ez_bar_curl',
      name: 'EZ-Bar Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Curved bar reduces wrist strain',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Biceps'],
      equipment: 'EZ-Bar',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'spider_curl',
      name: 'Spider Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Strict bicep curl over bench',
      caloriesPerMinute: 4.2,
      metValue: 4.2,
      musclesWorked: ['Biceps'],
      equipment: 'Bench, Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'reverse_curl',
      name: 'Reverse Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Overhand grip for forearm development',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Brachialis', 'Forearms'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),

    // ========== TRICEPS EXERCISES ==========
    Exercise(
      id: 'tricep_dips',
      name: 'Tricep Dips',
      category: ExerciseCategory.triceps,
      type: ExerciseType.bodyweight,
      description: 'Compound tricep exercise',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Triceps', 'Chest', 'Shoulders'],
      equipment: 'Dip Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'skull_crushers',
      name: 'Skull Crushers',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Isolation exercise for triceps',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Triceps'],
      equipment: 'Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'close_grip_bench',
      name: 'Close-Grip Bench Press',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Compound tricep builder',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Triceps', 'Chest'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'overhead_tricep_extension',
      name: 'Overhead Tricep Extension',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Stretches long head of tricep',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Triceps'],
      equipment: 'Dumbbell/Cable',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'tricep_pushdown',
      name: 'Tricep Pushdown',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Cable isolation for triceps',
      caloriesPerMinute: 4.3,
      metValue: 4.3,
      musclesWorked: ['Triceps'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'tricep_kickback',
      name: 'Tricep Kickback',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Single-arm tricep isolation',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Triceps'],
      equipment: 'Dumbbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'diamond_dips',
      name: 'Diamond Dips',
      category: ExerciseCategory.triceps,
      type: ExerciseType.bodyweight,
      description: 'Narrow dips for triceps',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Triceps'],
      equipment: 'Dip Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'rope_pushdown',
      name: 'Rope Pushdown',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Cable pushdown with rope attachment',
      caloriesPerMinute: 4.3,
      metValue: 4.3,
      musclesWorked: ['Triceps'],
      equipment: 'Cable Machine, Rope',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'jm_press',
      name: 'JM Press',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Hybrid between close-grip and skull crusher',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Triceps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'bench_dips',
      name: 'Bench Dips',
      category: ExerciseCategory.triceps,
      type: ExerciseType.bodyweight,
      description: 'Beginner-friendly tricep dips',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Triceps', 'Shoulders'],
      equipment: 'Bench',
      icon: Icons.accessibility_new,
    ),

    // ========== LEG EXERCISES ==========
    Exercise(
      id: 'squat',
      name: 'Barbell Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'King of leg exercises',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'leg_press',
      name: 'Leg Press',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Machine-based quad builder',
      caloriesPerMinute: 7.0,
      metValue: 7.0,
      musclesWorked: ['Quadriceps', 'Glutes'],
      equipment: 'Leg Press Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'lunges',
      name: 'Lunges',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Unilateral leg exercise',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'],
      icon: Icons.accessibility_new,
      isUnilateral: true,
    ),
    Exercise(
      id: 'leg_curl',
      name: 'Leg Curl',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Isolation for hamstrings',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Hamstrings'],
      equipment: 'Leg Curl Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'leg_extension',
      name: 'Leg Extension',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Quad isolation exercise',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Quadriceps'],
      equipment: 'Leg Extension Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'romanian_deadlift',
      name: 'Romanian Deadlift',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Hamstring and glute builder',
      caloriesPerMinute: 7.5,
      metValue: 7.5,
      musclesWorked: ['Hamstrings', 'Glutes', 'Lower Back'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'bulgarian_split_squat',
      name: 'Bulgarian Split Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Single-leg squat variation',
      caloriesPerMinute: 7.0,
      metValue: 7.5,
      musclesWorked: ['Quadriceps', 'Glutes'],
      equipment: 'Bench, Dumbbells',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'calf_raise',
      name: 'Calf Raise',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Isolation for calves',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Calves'],
      equipment: 'Machine or Bodyweight',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'front_squat',
      name: 'Front Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Quad-focused squat variation',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Quadriceps', 'Core', 'Upper Back'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'hack_squat',
      name: 'Hack Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Machine squat for quads',
      caloriesPerMinute: 7.5,
      metValue: 7.5,
      musclesWorked: ['Quadriceps', 'Glutes'],
      equipment: 'Hack Squat Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'goblet_squat',
      name: 'Goblet Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Squat holding weight at chest',
      caloriesPerMinute: 7.0,
      metValue: 7.0,
      musclesWorked: ['Quadriceps', 'Glutes', 'Core'],
      equipment: 'Dumbbell or Kettlebell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'walking_lunges',
      name: 'Walking Lunges',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Dynamic lunge variation',
      caloriesPerMinute: 7.0,
      metValue: 7.5,
      musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'pistol_squat',
      name: 'Pistol Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Advanced single-leg squat',
      caloriesPerMinute: 8.0,
      metValue: 9.0,
      musclesWorked: ['Quadriceps', 'Glutes', 'Core', 'Balance'],
      icon: Icons.accessibility_new,
      isUnilateral: true,
    ),
    Exercise(
      id: 'sumo_deadlift',
      name: 'Sumo Deadlift',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Wide-stance deadlift for glutes and inner thighs',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Glutes', 'Inner Thighs', 'Hamstrings'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'glute_bridge',
      name: 'Glute Bridge',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Hip thrust for glutes',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Glutes', 'Hamstrings'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'hip_thrust',
      name: 'Barbell Hip Thrust',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Primary glute builder',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Glutes', 'Hamstrings'],
      equipment: 'Barbell, Bench',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'nordic_curl',
      name: 'Nordic Hamstring Curl',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Advanced hamstring eccentric exercise',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Hamstrings'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'box_jump',
      name: 'Box Jump',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Explosive plyometric leg exercise',
      caloriesPerMinute: 8.5,
      metValue: 9.0,
      musclesWorked: ['Quadriceps', 'Glutes', 'Calves'],
      equipment: 'Plyo Box',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'single_leg_rdl',
      name: 'Single-Leg RDL',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Unilateral Romanian deadlift',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Hamstrings', 'Glutes', 'Balance'],
      equipment: 'Dumbbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'sissy_squat',
      name: 'Sissy Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Quad isolation bodyweight exercise',
      caloriesPerMinute: 6.0,
      metValue: 6.5,
      musclesWorked: ['Quadriceps'],
      icon: Icons.accessibility_new,
    ),

    // ========== CORE EXERCISES ==========
    Exercise(
      id: 'plank',
      name: 'Plank',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Isometric core strengthener',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Core', 'Shoulders'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'l_sit',
      name: 'L-Sit',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced isometric core and hip flexor hold',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Core', 'Hip Flexors', 'Shoulders', 'Triceps'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'crunches',
      name: 'Crunches',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Classic ab exercise',
      caloriesPerMinute: 4.0,
      metValue: 4.0,
      musclesWorked: ['Abs'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'leg_raises',
      name: 'Leg Raises',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Lower ab focus',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Lower Abs', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'hanging_leg_raise',
      name: 'Hanging Leg Raise',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced hanging ab exercise',
      caloriesPerMinute: 6.0,
      metValue: 6.5,
      musclesWorked: ['Lower Abs', 'Hip Flexors', 'Grip'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'russian_twist',
      name: 'Russian Twist',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Oblique strengthener',
      caloriesPerMinute: 5.5,
      metValue: 5.5,
      musclesWorked: ['Obliques', 'Abs'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'ab_wheel_rollout',
      name: 'Ab Wheel Rollout',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced ab exercise with wheel',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Abs', 'Shoulders', 'Lower Back'],
      equipment: 'Ab Wheel',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'dragon_flag',
      name: 'Dragon Flag',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Elite-level core exercise',
      caloriesPerMinute: 7.5,
      metValue: 8.5,
      musclesWorked: ['Abs', 'Lower Back', 'Hip Flexors'],
      equipment: 'Bench',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'bicycle_crunches',
      name: 'Bicycle Crunches',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Dynamic ab and oblique exercise',
      caloriesPerMinute: 5.0,
      metValue: 5.5,
      musclesWorked: ['Abs', 'Obliques'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'side_plank',
      name: 'Side Plank',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Oblique and lateral core stability',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Obliques', 'Core'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'mountain_climbers',
      name: 'Mountain Climbers',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Dynamic cardio core exercise',
      caloriesPerMinute: 8.0,
      metValue: 8.5,
      musclesWorked: ['Core', 'Hip Flexors', 'Shoulders'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'hollow_body_hold',
      name: 'Hollow Body Hold',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Gymnastic core position hold',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Abs', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'v_ups',
      name: 'V-Ups',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced ab crunch variation',
      caloriesPerMinute: 6.0,
      metValue: 6.5,
      musclesWorked: ['Abs', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'windshield_wipers',
      name: 'Windshield Wipers',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Hanging oblique rotation',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Obliques', 'Abs', 'Hip Flexors'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'toes_to_bar',
      name: 'Toes to Bar',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced hanging ab exercise',
      caloriesPerMinute: 7.0,
      metValue: 7.5,
      musclesWorked: ['Abs', 'Hip Flexors', 'Lats'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'dead_bug',
      name: 'Dead Bug',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Core stability and coordination',
      caloriesPerMinute: 4.5,
      metValue: 5.0,
      musclesWorked: ['Core', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'sit_ups',
      name: 'Sit-ups',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Full range ab exercise',
      caloriesPerMinute: 5.0,
      metValue: 5.5,
      musclesWorked: ['Abs', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'flutter_kicks',
      name: 'Flutter Kicks',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Lower ab and hip flexor endurance',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Lower Abs', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'plank_to_pike',
      name: 'Plank to Pike',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Dynamic plank variation',
      caloriesPerMinute: 6.0,
      metValue: 6.5,
      musclesWorked: ['Core', 'Shoulders', 'Hip Flexors'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'pallof_press',
      name: 'Pallof Press',
      category: ExerciseCategory.core,
      type: ExerciseType.strength,
      description: 'Anti-rotation core exercise',
      caloriesPerMinute: 4.5,
      metValue: 5.0,
      musclesWorked: ['Core', 'Obliques'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'reverse_crunch',
      name: 'Reverse Crunch',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Lower ab focused crunch',
      caloriesPerMinute: 4.8,
      metValue: 5.2,
      musclesWorked: ['Lower Abs'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'wood_choppers',
      name: 'Wood Choppers',
      category: ExerciseCategory.core,
      type: ExerciseType.strength,
      description: 'Rotational core exercise',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Obliques', 'Core', 'Shoulders'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),

    // ========== CARDIO EXERCISES ==========
    Exercise(
      id: 'running',
      name: 'Running',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'High-intensity cardio',
      caloriesPerMinute: 10.0,
      metValue: 10.0,
      musclesWorked: ['Legs', 'Cardiovascular System'],
      icon: Icons.directions_run,
    ),
    Exercise(
      id: 'sprinting',
      name: 'Sprinting',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Maximum intensity running',
      caloriesPerMinute: 15.0,
      metValue: 15.0,
      musclesWorked: ['Legs', 'Cardiovascular System'],
      icon: Icons.directions_run,
    ),
    Exercise(
      id: 'cycling',
      name: 'Cycling',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Low-impact cardio',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Legs', 'Cardiovascular System'],
      equipment: 'Bicycle',
      icon: Icons.directions_bike,
    ),
    Exercise(
      id: 'jump_rope',
      name: 'Jump Rope',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'High-intensity cardio',
      caloriesPerMinute: 12.0,
      metValue: 12.0,
      musclesWorked: ['Legs', 'Shoulders', 'Cardiovascular System'],
      equipment: 'Jump Rope',
      icon: Icons.sports_gymnastics,
    ),
    Exercise(
      id: 'rowing',
      name: 'Rowing',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Full-body cardio exercise',
      caloriesPerMinute: 11.0,
      metValue: 11.0,
      musclesWorked: ['Back', 'Legs', 'Arms', 'Cardiovascular System'],
      equipment: 'Rowing Machine',
      icon: Icons.rowing,
    ),
    Exercise(
      id: 'swimming',
      name: 'Swimming',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Full-body low-impact cardio',
      caloriesPerMinute: 9.0,
      metValue: 9.0,
      musclesWorked: ['Full Body', 'Cardiovascular System'],
      icon: Icons.pool,
    ),
    Exercise(
      id: 'stair_climber',
      name: 'Stair Climber',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Leg-focused cardio machine',
      caloriesPerMinute: 9.5,
      metValue: 9.5,
      musclesWorked: ['Legs', 'Glutes', 'Cardiovascular System'],
      equipment: 'Stair Climber Machine',
      icon: Icons.stairs,
    ),
    Exercise(
      id: 'elliptical',
      name: 'Elliptical',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Low-impact cardio machine',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Legs', 'Arms', 'Cardiovascular System'],
      equipment: 'Elliptical Machine',
      icon: Icons.directions_run,
    ),
    Exercise(
      id: 'battle_ropes',
      name: 'Battle Ropes',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'High-intensity upper body cardio',
      caloriesPerMinute: 10.5,
      metValue: 11.0,
      musclesWorked: ['Shoulders', 'Arms', 'Core', 'Cardiovascular System'],
      equipment: 'Battle Ropes',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'high_knees',
      name: 'High Knees',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'In-place running with high knees',
      caloriesPerMinute: 9.0,
      metValue: 9.5,
      musclesWorked: ['Legs', 'Hip Flexors', 'Cardiovascular System'],
      icon: Icons.directions_run,
    ),
    Exercise(
      id: 'jumping_jacks',
      name: 'Jumping Jacks',
      category: ExerciseCategory.cardio,
      type: ExerciseType.cardio,
      description: 'Classic full-body cardio',
      caloriesPerMinute: 8.0,
      metValue: 8.5,
      musclesWorked: ['Full Body', 'Cardiovascular System'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'sled_push',
      name: 'Sled Push',
      category: ExerciseCategory.cardio,
      type: ExerciseType.strength,
      description: 'High-intensity leg and conditioning exercise',
      caloriesPerMinute: 12.0,
      metValue: 12.5,
      musclesWorked: ['Legs', 'Core', 'Cardiovascular System'],
      equipment: 'Prowler Sled',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'sled_drag',
      name: 'Sled Drag',
      category: ExerciseCategory.cardio,
      type: ExerciseType.strength,
      description: 'Backward sled pulling',
      caloriesPerMinute: 11.0,
      metValue: 11.5,
      musclesWorked: ['Legs', 'Back', 'Cardiovascular System'],
      equipment: 'Prowler Sled',
      icon: Icons.fitness_center,
    ),

    // ========== FULL BODY EXERCISES ==========
    Exercise(
      id: 'burpees',
      name: 'Burpees',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.bodyweight,
      description: 'Full-body explosive exercise',
      caloriesPerMinute: 10.0,
      metValue: 10.0,
      musclesWorked: ['Full Body'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'thrusters',
      name: 'Thrusters',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Front squat to overhead press',
      caloriesPerMinute: 9.5,
      metValue: 10.0,
      musclesWorked: ['Legs', 'Shoulders', 'Core'],
      equipment: 'Barbell/Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'clean_and_press',
      name: 'Clean and Press',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Olympic lift variation',
      caloriesPerMinute: 10.0,
      metValue: 10.5,
      musclesWorked: ['Full Body'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'kettlebell_swing',
      name: 'Kettlebell Swing',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Hip hinge explosive movement',
      caloriesPerMinute: 9.0,
      metValue: 9.5,
      musclesWorked: ['Glutes', 'Hamstrings', 'Core', 'Shoulders'],
      equipment: 'Kettlebell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'man_makers',
      name: 'Man Makers',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Burpee with dumbbell rows and press',
      caloriesPerMinute: 11.0,
      metValue: 11.5,
      musclesWorked: ['Full Body'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'turkish_getup',
      name: 'Turkish Get-Up',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Complex full-body movement',
      caloriesPerMinute: 7.5,
      metValue: 8.0,
      musclesWorked: ['Full Body', 'Core', 'Shoulders'],
      equipment: 'Kettlebell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'bear_crawl',
      name: 'Bear Crawl',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.bodyweight,
      description: 'Quadrupedal locomotion',
      caloriesPerMinute: 8.0,
      metValue: 8.5,
      musclesWorked: ['Core', 'Shoulders', 'Legs'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'clean',
      name: 'Power Clean',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Olympic weightlifting movement',
      caloriesPerMinute: 10.0,
      metValue: 10.5,
      musclesWorked: ['Full Body', 'Explosiveness'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'snatch',
      name: 'Snatch',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Olympic lift - floor to overhead',
      caloriesPerMinute: 10.5,
      metValue: 11.0,
      musclesWorked: ['Full Body', 'Explosiveness'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'wall_ball',
      name: 'Wall Ball',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Squat and throw to target',
      caloriesPerMinute: 9.0,
      metValue: 9.5,
      musclesWorked: ['Legs', 'Shoulders', 'Core'],
      equipment: 'Medicine Ball',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'farmers_walk',
      name: 'Farmer\'s Walk',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Loaded carry for grip and core',
      caloriesPerMinute: 7.0,
      metValue: 7.5,
      musclesWorked: ['Grip', 'Traps', 'Core', 'Legs'],
      equipment: 'Dumbbells/Kettlebells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'devils_press',
      name: 'Devil\'s Press',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Burpee to dumbbell snatch',
      caloriesPerMinute: 11.5,
      metValue: 12.0,
      musclesWorked: ['Full Body'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'sprawl',
      name: 'Sprawl',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.bodyweight,
      description: 'Burpee without push-up',
      caloriesPerMinute: 9.5,
      metValue: 10.0,
      musclesWorked: ['Full Body', 'Cardiovascular System'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'rope_climb',
      name: 'Rope Climb',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.bodyweight,
      description: 'Vertical climbing exercise',
      caloriesPerMinute: 9.0,
      metValue: 9.5,
      musclesWorked: ['Back', 'Arms', 'Grip', 'Core'],
      equipment: 'Climbing Rope',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'inchworm',
      name: 'Inchworm',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.bodyweight,
      description: 'Walk-out to plank movement',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Core', 'Hamstrings', 'Shoulders'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'slam_ball',
      name: 'Slam Ball',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Explosive ball slam',
      caloriesPerMinute: 10.0,
      metValue: 10.5,
      musclesWorked: ['Full Body', 'Core'],
      equipment: 'Slam Ball',
      icon: Icons.fitness_center,
    ),

    // ========== ADDITIONAL CHEST VARIATIONS ==========
    Exercise(
      id: 'single_arm_dumbbell_press',
      name: 'Single-Arm Dumbbell Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Unilateral chest press',
      caloriesPerMinute: 6.2,
      metValue: 6.2,
      musclesWorked: ['Pectorals', 'Core', 'Triceps'],
      equipment: 'Dumbbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'clap_pushups',
      name: 'Clap Push-ups',
      category: ExerciseCategory.chest,
      type: ExerciseType.bodyweight,
      description: 'Plyometric push-up variation',
      caloriesPerMinute: 8.5,
      metValue: 9.0,
      musclesWorked: ['Pectorals', 'Triceps', 'Explosiveness'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'cable_flyes',
      name: 'Cable Flyes',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Standing cable chest fly',
      caloriesPerMinute: 4.8,
      metValue: 4.8,
      musclesWorked: ['Pectorals'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'pause_bench_press',
      name: 'Pause Bench Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Bench press with pause at bottom',
      caloriesPerMinute: 6.5,
      metValue: 6.5,
      musclesWorked: ['Pectorals', 'Triceps', 'Shoulders'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'guillotine_press',
      name: 'Guillotine Press',
      category: ExerciseCategory.chest,
      type: ExerciseType.strength,
      description: 'Bench press to neck for upper chest',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Upper Pectorals', 'Shoulders'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),

    // ========== ADDITIONAL BACK VARIATIONS ==========
    Exercise(
      id: 'one_arm_lat_pulldown',
      name: 'Single-Arm Lat Pulldown',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Unilateral lat pulldown',
      caloriesPerMinute: 5.8,
      metValue: 5.8,
      musclesWorked: ['Lats', 'Biceps'],
      equipment: 'Cable Machine',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),
    Exercise(
      id: 'commando_pullups',
      name: 'Commando Pull-ups',
      category: ExerciseCategory.back,
      type: ExerciseType.bodyweight,
      description: 'Parallel grip pull-ups',
      caloriesPerMinute: 7.8,
      metValue: 8.2,
      musclesWorked: ['Lats', 'Biceps', 'Core'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'weighted_pullups',
      name: 'Weighted Pull-ups',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Pull-ups with added weight',
      caloriesPerMinute: 8.5,
      metValue: 9.0,
      musclesWorked: ['Lats', 'Biceps', 'Rhomboids'],
      equipment: 'Pull-up Bar, Weight Belt',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'chest_supported_row',
      name: 'Chest-Supported Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Row on incline bench',
      caloriesPerMinute: 6.0,
      metValue: 6.0,
      musclesWorked: ['Upper Back', 'Lats'],
      equipment: 'Incline Bench, Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'kroc_row',
      name: 'Kroc Row',
      category: ExerciseCategory.back,
      type: ExerciseType.strength,
      description: 'Heavy single-arm row with momentum',
      caloriesPerMinute: 6.5,
      metValue: 6.5,
      musclesWorked: ['Lats', 'Upper Back', 'Grip'],
      equipment: 'Heavy Dumbbell',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),

    // ========== ADDITIONAL SHOULDER VARIATIONS ==========
    Exercise(
      id: 'bus_driver',
      name: 'Bus Driver',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Plate rotation for shoulder endurance',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Deltoids', 'Forearms'],
      equipment: 'Weight Plate',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'plate_raise',
      name: 'Plate Front Raise',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Front raise with weight plate',
      caloriesPerMinute: 4.2,
      metValue: 4.2,
      musclesWorked: ['Anterior Deltoids'],
      equipment: 'Weight Plate',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'bradford_press',
      name: 'Bradford Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Front to back shoulder press',
      caloriesPerMinute: 6.3,
      metValue: 6.3,
      musclesWorked: ['Deltoids', 'Traps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'cube_lateral_raise',
      name: 'Cuban Press',
      category: ExerciseCategory.shoulders,
      type: ExerciseType.strength,
      description: 'Complex shoulder rotation and press',
      caloriesPerMinute: 5.0,
      metValue: 5.0,
      musclesWorked: ['Deltoids', 'Rotator Cuff'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),

    // ========== ADDITIONAL ARM VARIATIONS ==========
    Exercise(
      id: '21s_bicep_curl',
      name: '21s Bicep Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: '7 bottom half + 7 top half + 7 full reps',
      caloriesPerMinute: 4.8,
      metValue: 4.8,
      musclesWorked: ['Biceps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'zottman_curl',
      name: 'Zottman Curl',
      category: ExerciseCategory.biceps,
      type: ExerciseType.strength,
      description: 'Curl up supinated, lower pronated',
      caloriesPerMinute: 4.5,
      metValue: 4.5,
      musclesWorked: ['Biceps', 'Forearms'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'tate_press',
      name: 'Tate Press',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Unique elbow extension angle',
      caloriesPerMinute: 4.3,
      metValue: 4.3,
      musclesWorked: ['Triceps'],
      equipment: 'Dumbbells',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'board_press',
      name: 'Board Press',
      category: ExerciseCategory.triceps,
      type: ExerciseType.strength,
      description: 'Partial range bench for triceps',
      caloriesPerMinute: 6.2,
      metValue: 6.2,
      musclesWorked: ['Triceps', 'Chest'],
      equipment: 'Barbell, Board',
      icon: Icons.fitness_center,
    ),

    // ========== ADDITIONAL LEG VARIATIONS ==========
    Exercise(
      id: 'zercher_squat',
      name: 'Zercher Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Squat holding barbell in elbow crooks',
      caloriesPerMinute: 8.2,
      metValue: 8.5,
      musclesWorked: ['Quadriceps', 'Glutes', 'Core', 'Biceps'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'jefferson_squat',
      name: 'Jefferson Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Straddle deadlift/squat hybrid',
      caloriesPerMinute: 7.8,
      metValue: 8.0,
      musclesWorked: ['Quadriceps', 'Glutes', 'Obliques'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'deficit_deadlift',
      name: 'Deficit Deadlift',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Deadlift standing on platform',
      caloriesPerMinute: 8.5,
      metValue: 8.5,
      musclesWorked: ['Hamstrings', 'Glutes', 'Lower Back'],
      equipment: 'Barbell, Platform',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'anderson_squat',
      name: 'Anderson Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Squat starting from bottom in rack',
      caloriesPerMinute: 8.0,
      metValue: 8.0,
      musclesWorked: ['Quadriceps', 'Glutes'],
      equipment: 'Barbell, Rack',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'curtsy_lunge',
      name: 'Curtsy Lunge',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Crossover lunge for glutes',
      caloriesPerMinute: 6.8,
      metValue: 7.0,
      musclesWorked: ['Glutes', 'Quadriceps', 'Inner Thighs'],
      icon: Icons.accessibility_new,
      isUnilateral: true,
    ),
    Exercise(
      id: 'cossack_squat',
      name: 'Cossack Squat',
      category: ExerciseCategory.legs,
      type: ExerciseType.bodyweight,
      description: 'Side-to-side deep squat',
      caloriesPerMinute: 7.0,
      metValue: 7.5,
      musclesWorked: ['Quadriceps', 'Adductors', 'Glutes'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'single_leg_press',
      name: 'Single-Leg Press',
      category: ExerciseCategory.legs,
      type: ExerciseType.strength,
      description: 'Unilateral leg press',
      caloriesPerMinute: 7.2,
      metValue: 7.5,
      musclesWorked: ['Quadriceps', 'Glutes'],
      equipment: 'Leg Press Machine',
      icon: Icons.fitness_center,
      isUnilateral: true,
    ),

    // ========== ADDITIONAL CORE VARIATIONS ==========
    Exercise(
      id: 'copenhagen_plank',
      name: 'Copenhagen Plank',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Side plank with leg abduction',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Obliques', 'Adductors', 'Core'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'human_flag',
      name: 'Human Flag',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced horizontal body hold',
      caloriesPerMinute: 7.5,
      metValue: 8.5,
      musclesWorked: ['Obliques', 'Lats', 'Core', 'Shoulders'],
      equipment: 'Pole',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'front_lever',
      name: 'Front Lever',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Elite horizontal pull hold',
      caloriesPerMinute: 7.0,
      metValue: 8.0,
      musclesWorked: ['Lats', 'Core', 'Shoulders'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'back_lever',
      name: 'Back Lever',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Advanced gymnastic hold',
      caloriesPerMinute: 7.0,
      metValue: 8.0,
      musclesWorked: ['Shoulders', 'Back', 'Core'],
      equipment: 'Pull-up Bar or Rings',
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'turkish_crunch',
      name: 'Turkish Crunch',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Alternating V-up variation',
      caloriesPerMinute: 5.5,
      metValue: 6.0,
      musclesWorked: ['Abs', 'Obliques'],
      icon: Icons.accessibility_new,
    ),
    Exercise(
      id: 'garhammer_raise',
      name: 'Garhammer Raise',
      category: ExerciseCategory.core,
      type: ExerciseType.bodyweight,
      description: 'Hanging knee tuck to L-sit',
      caloriesPerMinute: 6.5,
      metValue: 7.0,
      musclesWorked: ['Lower Abs', 'Hip Flexors'],
      equipment: 'Pull-up Bar',
      icon: Icons.accessibility_new,
    ),

    // ========== ADDITIONAL FULL BODY & OLYMPIC ==========
    Exercise(
      id: 'hang_clean',
      name: 'Hang Clean',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Clean from hang position',
      caloriesPerMinute: 9.5,
      metValue: 10.0,
      musclesWorked: ['Full Body', 'Explosiveness'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'hang_snatch',
      name: 'Hang Snatch',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Snatch from hang position',
      caloriesPerMinute: 10.0,
      metValue: 10.5,
      musclesWorked: ['Full Body', 'Explosiveness'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'clean_jerk',
      name: 'Clean and Jerk',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Full Olympic lift',
      caloriesPerMinute: 10.5,
      metValue: 11.0,
      musclesWorked: ['Full Body', 'Explosiveness'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'complex_barbell',
      name: 'Barbell Complex',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Multiple exercises without putting bar down',
      caloriesPerMinute: 11.0,
      metValue: 11.5,
      musclesWorked: ['Full Body', 'Conditioning'],
      equipment: 'Barbell',
      icon: Icons.fitness_center,
    ),
    Exercise(
      id: 'sandbag_carry',
      name: 'Sandbag Carry',
      category: ExerciseCategory.fullBody,
      type: ExerciseType.strength,
      description: 'Loaded carry with sandbag',
      caloriesPerMinute: 7.5,
      metValue: 8.0,
      musclesWorked: ['Full Body', 'Core', 'Grip'],
      equipment: 'Sandbag',
      icon: Icons.fitness_center,
    ),
  ];

  static Exercise? getExerciseById(String id) {
    try {
      return exercises.firstWhere((e) => e.id == id);
    } catch (e) {
      return null;
    }
  }

  static List<Exercise> getExercisesByCategory(ExerciseCategory category) {
    return exercises.where((e) => e.category == category).toList();
  }

  static List<Exercise> getExercisesByType(ExerciseType type) {
    return exercises.where((e) => e.type == type).toList();
  }

  static String getCategoryName(ExerciseCategory category) {
    switch (category) {
      case ExerciseCategory.chest:
        return 'Chest';
      case ExerciseCategory.back:
        return 'Back';
      case ExerciseCategory.shoulders:
        return 'Shoulders';
      case ExerciseCategory.biceps:
        return 'Biceps';
      case ExerciseCategory.triceps:
        return 'Triceps';
      case ExerciseCategory.legs:
        return 'Legs';
      case ExerciseCategory.core:
        return 'Core';
      case ExerciseCategory.cardio:
        return 'Cardio';
      case ExerciseCategory.fullBody:
        return 'Full Body';
    }
  }

  static IconData getCategoryIcon(ExerciseCategory category) {
    switch (category) {
      case ExerciseCategory.chest:
        return Icons.fitness_center;
      case ExerciseCategory.back:
        return Icons.fitness_center;
      case ExerciseCategory.shoulders:
        return Icons.fitness_center;
      case ExerciseCategory.biceps:
        return Icons.fitness_center;
      case ExerciseCategory.triceps:
        return Icons.fitness_center;
      case ExerciseCategory.legs:
        return Icons.directions_walk;
      case ExerciseCategory.core:
        return Icons.accessibility_new;
      case ExerciseCategory.cardio:
        return Icons.directions_run;
      case ExerciseCategory.fullBody:
        return Icons.accessibility_new;
    }
  }
}
