// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaNXY_dmb7cV9iFWffX-2B6e13Tbichx0',
    appId: '1:561391430514:android:ea1d848d92b7289eb10beb',
    messagingSenderId: '561391430514',
    projectId: 'vertex-ai-1618',
    databaseURL: 'https://vertex-ai-1618-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vertex-ai-1618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFIo-pezcOsrVZXGMymGwwNNyZ1eVUpUQ',
    appId: '1:561391430514:ios:7bfd48ae073a5869b10beb',
    messagingSenderId: '561391430514',
    projectId: 'vertex-ai-1618',
    databaseURL: 'https://vertex-ai-1618-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vertex-ai-1618.firebasestorage.app',
    androidClientId: '561391430514-4146b6ulvo0gvcmor771ftckb84tbpbg.apps.googleusercontent.com',
    iosClientId: '561391430514-82vhknitjnj5urjdkhk5nnp7d44d00vn.apps.googleusercontent.com',
    iosBundleId: 'com.vertex.ally',
  );
}
