// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE4lKRadCTcp_DNtrhSn2UHyQyrpX_9bk',
    appId: '1:362105572173:web:e9a423e64bba2a13e14504',
    messagingSenderId: '362105572173',
    projectId: 'project-f90df',
    authDomain: 'project-f90df.firebaseapp.com',
    storageBucket: 'project-f90df.firebasestorage.app',
    measurementId: 'G-8QL7E0R42B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmAJqTXePmFSEamh95vkBEk5zYpiVr4A',
    appId: '1:362105572173:ios:c5b83f52e6cbaf4de14504',
    messagingSenderId: '362105572173',
    projectId: 'project-f90df',
    storageBucket: 'project-f90df.firebasestorage.app',
    iosBundleId: 'com.vertex.ally',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj_jx8pwB0wtfVa_w_I9UkPDzb2QSHP_I',
    appId: '1:362105572173:android:10c9b5c36f288d12e14504',
    messagingSenderId: '362105572173',
    projectId: 'project-f90df',
    storageBucket: 'project-f90df.firebasestorage.app',
  );
}
