import 'package:ally/app.dart';
import 'package:ally/firebase.dart'; // Generated by flutterfire configure
import 'package:ally/language.dart';
import 'package:ally/lifecycle.dart';
import 'package:ally/notifications/introvert.dart';
import 'package:ally/providers/health.dart';
import 'package:ally/server/user.dart';
import 'package:ally/services/sleep.dart';
import 'package:ally/theme.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Global flag to check if Firebase is available
bool isFirebaseInitialized = false;

// Global navigator key to allow navigation and overlay access without context
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialize Firebase (Safe Mode)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    isFirebaseInitialized = true;
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
    // App continues running in "Offline Mode" if Firebase fails
    isFirebaseInitialized = false;
  }

  // 2. Initialize Critical Services
  FlutterForegroundTask.initCommunicationPort();
  await SleepTrackerService().loadSettings();

  // 3. Load User Preferences (Theme & Language)
  // This prevents the "white flash" by setting the theme before the app mounts.
  final prefs = await SharedPreferences.getInstance();
  final String savedTheme = prefs.getString('selectedTheme') ?? 'light';

  // 4. Lock Orientation (Optional, recommended for health apps)
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  // 5. Run App with MultiProvider
  runApp(
    MultiProvider(
      providers: [
        // Theme Management
        ChangeNotifierProvider(create: (_) => ThemeProvider(savedTheme)),

        // Language Management
        ChangeNotifierProvider(create: (_) => LocaleProvider()),

        // User & Auth Management
        ChangeNotifierProvider(create: (_) => UserProvider()),

        // Health Data (Steps, Water, Calories, etc.)
        ChangeNotifierProvider(create: (_) => HealthProvider()),

        // Notification Service (Introvert)
        Provider<IntrovertNotificationService>(
          create: (_) => IntrovertNotificationService(navigatorKey: navigatorKey),
        ),
      ],
      child: Ally(
        navigatorKey: navigatorKey,
        startupScreen: const AppLifecycleManager(),
      ),
    ),
  );
}