import 'package:ally/app.dart';
import 'package:ally/firebase_options.dart'; // Generated by flutterfire configure
import 'package:ally/language.dart';
import 'package:ally/lifecycle.dart';
import 'package:ally/notifications/introvert.dart';
import 'package:ally/notifications/extrovert.dart';
import 'package:ally/providers/health.dart';
import 'package:ally/server/user.dart';
import 'package:ally/services/sleep.dart';
import 'package:ally/theme.dart';
import 'package:ally/providers/workout.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Global flag to check if Firebase is available
bool isFirebaseInitialized = false;

// Global navigator key to allow navigation and overlay access without context
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialize Firebase on all supported platforms (including Web now)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    isFirebaseInitialized = true;
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
    // App continues running in "Offline Mode" if Firebase fails
    isFirebaseInitialized = false;
  } 

  // 2. Initialize Critical Services
  // Foreground task / Android background service APIs are not supported on web.
  if (!kIsWeb) {
    FlutterForegroundTask.initCommunicationPort();
  }

  await SleepTrackerService().loadSettings();

  // 3. Load User Preferences (Theme & Language)
  // This prevents the "white flash" by setting the theme before the app mounts.
  final prefs = await SharedPreferences.getInstance();
  final String savedTheme = prefs.getString('selectedTheme') ?? 'light';

  // 4. Lock Orientation (Optional, recommended for health apps)
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  // 5. Run App with MultiProvider
  runApp(
    MultiProvider(
      providers: [
        // Theme Management
        ChangeNotifierProvider(create: (_) => ThemeProvider(savedTheme)),

        // Language Management
        ChangeNotifierProvider(create: (_) => LocaleProvider()),

        // User & Auth Management
        ChangeNotifierProvider(create: (_) => UserProvider()),

        // Health Data (Steps, Water, Calories, etc.)
        ChangeNotifierProvider(create: (_) => HealthProvider()),

        // Workout Data
        ChangeNotifierProvider(create: (_) => WorkoutProvider()),

        // Notification Service (Introvert)
        Provider<IntrovertNotificationService>(
          create: (_) => IntrovertNotificationService(navigatorKey: navigatorKey),
        ),

        // External Notification Service (Extrovert)
        Provider<ExtrovertNotificationService>(
          create: (_) => ExtrovertNotificationService(navigatorKey: navigatorKey),
        ),
      ],
      // Doğrudan yükleme yerine Firebase durumunu garanti eden güvenli sarmalayıcı
      child: FirebaseSafeWrapper(
        navigatorKey: navigatorKey,
      ),
    ),
  );
}

/// Firebase servislerinin asenkron başlatılma boşluğunda Provider'ların 
/// çökmesini engelleyen güvenli ara katman widget'ı.
class FirebaseSafeWrapper extends StatelessWidget {
  final GlobalKey<NavigatorState> navigatorKey;

  const FirebaseSafeWrapper({
    super.key,
    required this.navigatorKey,
  });

  @override
  Widget build(BuildContext context) {
    // Eğer Firebase zaten main içinde saniyeler içinde başarıyla bağlandıysa 
    // doğrudan uygulamayı çökmeden başlatır.
    if (isFirebaseInitialized) {
      return Ally(
        navigatorKey: navigatorKey,
        startupScreen: const AppLifecycleManager(),
      );
    }

    // Eğer bir aksilik olduysa ve asenkron bekleme henüz bitmediyse, 
    // kısa bir süre güvenli bir şekilde arka planda asenkron süreci bekler.
    return FutureBuilder(
      future: Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      ),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const MaterialApp(
            debugShowCheckedModeBanner: false,
            home: Scaffold(
              body: Center(
                child: CircularProgressIndicator(),
              ),
            ),
          );
        }

        if (snapshot.hasError) {
          debugPrint('Firebase safe wrapper failed: ${snapshot.error}');
        }

        return Ally(
          navigatorKey: navigatorKey,
          startupScreen: const AppLifecycleManager(),
        );
      },
    );
  }
}
